version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app/
      - ./env:/app/env
    environment:
      UVICORN_WORKERS: 4
      DB_URL: postgresql://moon_explorer_user:Password!@postgres:5432/moon_explorer_db
    depends_on:
      - postgres

  postgres:
    container_name: postgres_db
    image: postgres
    hostname: postgres
    volumes:
      - "/postgres-data/:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    expose:
      - "5432"
    environment:
      POSTGRES_USER: moon_explorer_user
      POSTGRES_PASSWORD: Password!
      POSTGRES_DB: moon_explorer_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U moon_explorer_user -d moon_explorer_db -h localhost -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "7000:80"
    volumes:
      # TODO: improve the symlink
      - ./nginx/sites-available/default-ssl:/etc/nginx/conf.d/default.conf
      - ./nginx/sites-available/default-ssl:/etc/nginx/sites-enabled/default-ssl:ro
      - ./nginx/snippets:/etc/nginx/snippets:ro
    depends_on:
      - lunchlog
    expose:
      - 7000
    networks:
      - backend
      - default

volumes:
  postgres_data: