"""Initial migration

Revision ID: 8697204841d6
Revises: 9bc5fe54de13
Create Date: 2025-07-29 23:20:29.148930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8697204841d6'
down_revision: Union[str, Sequence[str], None] = '9bc5fe54de13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### command auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_robot_state_timestamp'), table_name='robot_state')
    op.drop_table('robot_state')
    op.drop_table('command_history')
    # ### end Alembic command ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### command auto generated by Alembic - please adjust! ###
    op.create_table('command_history',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('command_history_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('command', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('executed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('result', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='command_history_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('robot_state',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('x', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('y', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('direction', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('command_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['command_id'], ['command_history.id'], name=op.f('robot_state_command_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('robot_state_pkey'))
    )
    op.create_index(op.f('ix_robot_state_timestamp'), 'robot_state', ['timestamp'], unique=False)
    # ### end Alembic command ###
