"""Initial migration

Revision ID: 9bc5fe54de13
Revises: 
Create Date: 2025-07-29 23:19:38.426609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bc5fe54de13'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### command auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic command ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### command auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic command ###
